// Code generated by protoc-gen-go. DO NOT EDIT.
// source: types/account_state_blob.proto

package types

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type AccountStateBlob struct {
	Blob                 []byte   `protobuf:"bytes,1,opt,name=blob,proto3" json:"blob,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AccountStateBlob) Reset()         { *m = AccountStateBlob{} }
func (m *AccountStateBlob) String() string { return proto.CompactTextString(m) }
func (*AccountStateBlob) ProtoMessage()    {}
func (*AccountStateBlob) Descriptor() ([]byte, []int) {
	return fileDescriptor_d57bd59f79e8ae9e, []int{0}
}

func (m *AccountStateBlob) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AccountStateBlob.Unmarshal(m, b)
}
func (m *AccountStateBlob) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AccountStateBlob.Marshal(b, m, deterministic)
}
func (m *AccountStateBlob) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AccountStateBlob.Merge(m, src)
}
func (m *AccountStateBlob) XXX_Size() int {
	return xxx_messageInfo_AccountStateBlob.Size(m)
}
func (m *AccountStateBlob) XXX_DiscardUnknown() {
	xxx_messageInfo_AccountStateBlob.DiscardUnknown(m)
}

var xxx_messageInfo_AccountStateBlob proto.InternalMessageInfo

func (m *AccountStateBlob) GetBlob() []byte {
	if m != nil {
		return m.Blob
	}
	return nil
}

type AccountStateWithProof struct {
	Version              uint64             `protobuf:"varint,1,opt,name=version,proto3" json:"version,omitempty"`
	Blob                 *AccountStateBlob  `protobuf:"bytes,2,opt,name=blob,proto3" json:"blob,omitempty"`
	Proof                *AccountStateProof `protobuf:"bytes,3,opt,name=proof,proto3" json:"proof,omitempty"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *AccountStateWithProof) Reset()         { *m = AccountStateWithProof{} }
func (m *AccountStateWithProof) String() string { return proto.CompactTextString(m) }
func (*AccountStateWithProof) ProtoMessage()    {}
func (*AccountStateWithProof) Descriptor() ([]byte, []int) {
	return fileDescriptor_d57bd59f79e8ae9e, []int{1}
}

func (m *AccountStateWithProof) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AccountStateWithProof.Unmarshal(m, b)
}
func (m *AccountStateWithProof) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AccountStateWithProof.Marshal(b, m, deterministic)
}
func (m *AccountStateWithProof) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AccountStateWithProof.Merge(m, src)
}
func (m *AccountStateWithProof) XXX_Size() int {
	return xxx_messageInfo_AccountStateWithProof.Size(m)
}
func (m *AccountStateWithProof) XXX_DiscardUnknown() {
	xxx_messageInfo_AccountStateWithProof.DiscardUnknown(m)
}

var xxx_messageInfo_AccountStateWithProof proto.InternalMessageInfo

func (m *AccountStateWithProof) GetVersion() uint64 {
	if m != nil {
		return m.Version
	}
	return 0
}

func (m *AccountStateWithProof) GetBlob() *AccountStateBlob {
	if m != nil {
		return m.Blob
	}
	return nil
}

func (m *AccountStateWithProof) GetProof() *AccountStateProof {
	if m != nil {
		return m.Proof
	}
	return nil
}

func init() {
	proto.RegisterType((*AccountStateBlob)(nil), "types.AccountStateBlob")
	proto.RegisterType((*AccountStateWithProof)(nil), "types.AccountStateWithProof")
}

func init() { proto.RegisterFile("types/account_state_blob.proto", fileDescriptor_d57bd59f79e8ae9e) }

var fileDescriptor_d57bd59f79e8ae9e = []byte{
	// 215 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x92, 0x2b, 0xa9, 0x2c, 0x48,
	0x2d, 0xd6, 0x4f, 0x4c, 0x4e, 0xce, 0x2f, 0xcd, 0x2b, 0x89, 0x2f, 0x2e, 0x49, 0x2c, 0x49, 0x8d,
	0x4f, 0xca, 0xc9, 0x4f, 0xd2, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x05, 0xcb, 0x4b, 0x09,
	0x42, 0x94, 0x15, 0x14, 0xe5, 0xe7, 0xa7, 0x41, 0x64, 0x94, 0xd4, 0xb8, 0x04, 0x1c, 0x21, 0xba,
	0x82, 0x41, 0x9a, 0x9c, 0x72, 0xf2, 0x93, 0x84, 0x84, 0xb8, 0x58, 0x40, 0x7a, 0x25, 0x18, 0x15,
	0x18, 0x35, 0x78, 0x82, 0xc0, 0x6c, 0xa5, 0x3e, 0x46, 0x2e, 0x51, 0x64, 0x85, 0xe1, 0x99, 0x25,
	0x19, 0x01, 0x20, 0x73, 0x84, 0x24, 0xb8, 0xd8, 0xcb, 0x52, 0x8b, 0x8a, 0x33, 0xf3, 0xf3, 0xc0,
	0x1a, 0x58, 0x82, 0x60, 0x5c, 0x21, 0x6d, 0xa8, 0x39, 0x4c, 0x0a, 0x8c, 0x1a, 0xdc, 0x46, 0xe2,
	0x7a, 0x60, 0xdb, 0xf5, 0xd0, 0xad, 0x83, 0x58, 0x20, 0xa4, 0xc7, 0xc5, 0x0a, 0x76, 0x97, 0x04,
	0x33, 0x58, 0xb5, 0x04, 0x16, 0xd5, 0x60, 0xfb, 0x82, 0x20, 0xca, 0x9c, 0x4c, 0xa2, 0x8c, 0xd2,
	0x33, 0x4b, 0x32, 0x4a, 0x93, 0xf4, 0x92, 0xf3, 0x73, 0xf5, 0x73, 0x32, 0x93, 0x8a, 0x12, 0x75,
	0x8b, 0x33, 0xd3, 0x8b, 0x61, 0xcc, 0x94, 0x6c, 0xdd, 0xf4, 0x7c, 0x08, 0x47, 0xbf, 0xa8, 0x20,
	0x59, 0x1f, 0x6c, 0x5c, 0x12, 0x1b, 0xd8, 0xd7, 0xc6, 0x80, 0x00, 0x00, 0x00, 0xff, 0xff, 0x44,
	0x7d, 0xe2, 0xd3, 0x31, 0x01, 0x00, 0x00,
}
