// Code generated by protoc-gen-go. DO NOT EDIT.
// source: types/language_storage.proto

package types

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

/// The unique identifier for a module on the chain.
type ModuleId struct {
	Address              []byte   `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ModuleId) Reset()         { *m = ModuleId{} }
func (m *ModuleId) String() string { return proto.CompactTextString(m) }
func (*ModuleId) ProtoMessage()    {}
func (*ModuleId) Descriptor() ([]byte, []int) {
	return fileDescriptor_4afd49872b7cbf8e, []int{0}
}

func (m *ModuleId) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ModuleId.Unmarshal(m, b)
}
func (m *ModuleId) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ModuleId.Marshal(b, m, deterministic)
}
func (m *ModuleId) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ModuleId.Merge(m, src)
}
func (m *ModuleId) XXX_Size() int {
	return xxx_messageInfo_ModuleId.Size(m)
}
func (m *ModuleId) XXX_DiscardUnknown() {
	xxx_messageInfo_ModuleId.DiscardUnknown(m)
}

var xxx_messageInfo_ModuleId proto.InternalMessageInfo

func (m *ModuleId) GetAddress() []byte {
	if m != nil {
		return m.Address
	}
	return nil
}

func (m *ModuleId) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func init() {
	proto.RegisterType((*ModuleId)(nil), "types.ModuleId")
}

func init() { proto.RegisterFile("types/language_storage.proto", fileDescriptor_4afd49872b7cbf8e) }

var fileDescriptor_4afd49872b7cbf8e = []byte{
	// 152 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x92, 0x29, 0xa9, 0x2c, 0x48,
	0x2d, 0xd6, 0xcf, 0x49, 0xcc, 0x4b, 0x2f, 0x4d, 0x4c, 0x4f, 0x8d, 0x2f, 0x2e, 0xc9, 0x2f, 0x4a,
	0x4c, 0x4f, 0xd5, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x05, 0xcb, 0x2a, 0x59, 0x70, 0x71,
	0xf8, 0xe6, 0xa7, 0x94, 0xe6, 0xa4, 0x7a, 0xa6, 0x08, 0x49, 0x70, 0xb1, 0x27, 0xa6, 0xa4, 0x14,
	0xa5, 0x16, 0x17, 0x4b, 0x30, 0x2a, 0x30, 0x6a, 0xf0, 0x04, 0xc1, 0xb8, 0x42, 0x42, 0x5c, 0x2c,
	0x79, 0x89, 0xb9, 0xa9, 0x12, 0x4c, 0x0a, 0x8c, 0x1a, 0x9c, 0x41, 0x60, 0xb6, 0x93, 0x49, 0x94,
	0x51, 0x7a, 0x66, 0x49, 0x46, 0x69, 0x92, 0x5e, 0x72, 0x7e, 0xae, 0x7e, 0x4e, 0x66, 0x52, 0x51,
	0xa2, 0x6e, 0x71, 0x66, 0x7a, 0x31, 0x8c, 0x99, 0x92, 0xad, 0x9b, 0x9e, 0x0f, 0xe1, 0xe8, 0x17,
	0x15, 0x24, 0xeb, 0x83, 0xed, 0x4b, 0x62, 0x03, 0xdb, 0x6e, 0x0c, 0x08, 0x00, 0x00, 0xff, 0xff,
	0xa3, 0xed, 0xc6, 0x2c, 0x9d, 0x00, 0x00, 0x00,
}
